@host = https://api-billing.idxboost.dev/api

# POST CUSTOMERS
POST {{host}}/list-customers-v2
Content-Type: application/json

{
    "page": 1
}

### GET BOARDS
POST https://backoffice.idxboost.dev/tgapi/api/getBoards