const {
  VITE_APP_API_BILLING_HOST,
  VITE_APP_API_PACKAGE_BUILDER,
  VITE_APP_API_BACKOFFICE,
  VITE_APP_API_STRIPE,
} = import.meta.env

export const API = {
  _BILLING_HOST:
    (window.API_BILLING_HOST || VITE_APP_API_BILLING_HOST) + "/api",
  _PACKAGE_BUILDER:
    (window.API_PACKAGE_BUILDER || VITE_APP_API_PACKAGE_BUILDER) + "/api",
  _BACKOFFICE:
    (window.API_BACKOFFICE || VITE_APP_API_BACKOFFICE) + "/tgapi/api",
  _STRIPE: (window.API_STRIPE || VITE_APP_API_STRIPE) + "/api",
}
